# Generated by Django 5.2.10 on 2026-01-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_answer_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='image URL'),
        ),
    ]
