# Generated by Django 5.2.10 on 2026-01-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('ADMIN', 'Administrator')], default='EMPLOYEE', max_length=50, verbose_name='role'),
        ),
    ]
