# Generated by Django 5.2.10 on 2026-01-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
